# Generated by Django 5.0 on 2023-12-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JogoVelha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_1', models.CharField(default='-', max_length=1)),
                ('posicao_2', models.CharField(default='-', max_length=1)),
                ('posicao_3', models.CharField(default='-', max_length=1)),
                ('posicao_4', models.CharField(default='-', max_length=1)),
                ('posicao_5', models.CharField(default='-', max_length=1)),
                ('posicao_6', models.CharField(default='-', max_length=1)),
                ('posicao_7', models.CharField(default='-', max_length=1)),
                ('posicao_8', models.CharField(default='-', max_length=1)),
                ('posicao_9', models.CharField(default='-', max_length=1)),
            ],
        ),
    ]
